### ISSUE TITLE
Wrong group box style

### ISSUE THREAD

**Issue by CDrummond** [MartinBriza/adwaita-qt#57]
The current Adwaita-Qt groupbox style does not match Gtk/GNOME:

1. Groupbox should not have a frame
2. Title should be bold
3. Title should be left aligned - not centered

**Comment by MartinBriza** [comment]
Thank you for noticing. I'll fix that for the following release.

**Comment by MartinBriza** [comment]
In the context of GNOME, not having borders definitely makes sense because the application designers already have that in mind. Some Qt/KDE applications however may look really confusing without the borders.
Following the GNOME guidelines to 100% may not be beneficial in some cases.

I'll merge your pull request but in case somebody comes with a screenshot where it's hard to determine which group is which, I'll put the frames back.

Thank you for the patch!
